### ISSUE TITLE
pip install doesn't work with Python 3.x

### ISSUE THREAD

**Issue by hugovk** [hugovk/Clonedigger-Exhumed#1]
To reproduce:

To install from PyPi:
`pip install clonedigger`

To install from local directory:
`pip install -e .`

Expected result:
1. Clone Digger installs
2. Can run `clonedigger` on some source.

Actual result:
Installs ok with Python 2.6 and 2.7.
Doesn't install with Python 3.2 and 3.3:

See this build for example where 2.x installs and 3.x doesn't:
https://travis-ci.org/hugovk/Clonedigger-Exhumed/builds/20350647

```
$ pip install -e .
Obtaining file:///home/travis/build/hugovk/Clonedigger-Exhumed
  Running setup.py (path:/home/travis/build/hugovk/Clonedigger-Exhumed/setup.py) egg_info for package from file:///home/travis/build/hugovk/Clonedigger-Exhumed
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/travis/build/hugovk/Clonedigger-Exhumed/setup.py", line 6, in <module>
        from ez_setup import use_setuptools
      File "ez_setup.py", line 94
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/travis/build/hugovk/Clonedigger-Exhumed/setup.py", line 6, in <module>
    from ez_setup import use_setuptools
  File "ez_setup.py", line 94
    except pkg_resources.VersionConflict, e:
                                        ^
SyntaxError: invalid syntax
```

**Comment by hugovk** [comment]
Next problem: uses 2.x style `print`:

```
pip install -e .
Obtaining file:///home/travis/build/hugovk/Clonedigger-Exhumed
  Running setup.py (path:/home/travis/build/hugovk/Clonedigger-Exhumed/setup.py) egg_info for package from file:///home/travis/build/hugovk/Clonedigger-Exhumed
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/travis/build/hugovk/Clonedigger-Exhumed/setup.py", line 6, in <module>
        from ez_setup import use_setuptools
      File "./ez_setup.py", line 229
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/travis/build/hugovk/Clonedigger-Exhumed/setup.py", line 6, in <module>
    from ez_setup import use_setuptools
  File "./ez_setup.py", line 229
    print "Setuptools version",version,"or greater has been installed."
                             ^
SyntaxError: invalid syntax
```

https://travis-ci.org/hugovk/Clonedigger-Exhumed/jobs/20351200
